### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by bewee**

### CODE REVIEW

**Comment by lu-zero** [comment]
Please land https://github.com/WebThingsIO/webthing-rust/pull/63 first :)

**Comment by bewee** [comment]
Yes, both are just waiting for @tim-hellhake

**Review by tim-hellhake — APPROVED** [review]
Looks good to me.
You just need to add the #63 pr to the changelog.

**Comment by reitermarkus** [comment]
Thanks!

**Pull request merged**
